import { db } from "./drizzle";
import { workshops } from "./schema";

const ADMIN_USER_ID = "L3USi2X66cZpFhIBegzYX3zctsqXJ1cp"; // replace with real user.id

export async function seedWorkshops() {
  await db.insert(workshops).values([
    {
      slug: "react-js-live-workshop",
      title: "React.js Live Workshop",
      description:
        "Hands-on React.js workshop covering hooks, components, and best practices.",
      createdBy: ADMIN_USER_ID,
      category: "Web Development",
      language: "English",
      level: "Beginner",
      date: "2025-02-10",
      time: "10:00 AM",
      duration: "3 hours",
      price: "999",
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?react,javascript",
      status: "approved",
    },
    {
      slug: "nodejs-backend-mastery",
      title: "Node.js Backend Mastery",
      description:
        "Build scalable REST APIs with Node.js, Express, and PostgreSQL.",
      createdBy: ADMIN_USER_ID,
      category: "Backend",
      language: "English",
      level: "Intermediate",
      date: "2025-02-12",
      time: "02:00 PM",
      duration: "4 hours",
      price: "1499",
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?nodejs,backend",
      status: "approved",
    },
    {
      slug: "fullstack-mern-bootcamp",
      title: "Full-Stack MERN Bootcamp",
      description: "Complete MERN stack training with real-world projects.",
      createdBy: ADMIN_USER_ID,
      category: "Fullstack",
      language: "English",
      level: "Intermediate",
      date: "2025-02-15",
      time: "09:00 AM",
      duration: "6 hours",
      price: "2999",
      mode: "both",
      address: "Bangalore Tech Hub",
      thumbnailUrl:
        "https://source.unsplash.com/featured/?programming,developer",
      status: "pending",
    },
    {
      slug: "ui-ux-design-principles",
      title: "UI/UX Design Principles",
      description: "Learn UI/UX fundamentals, wireframes, and user psychology.",
      createdBy: ADMIN_USER_ID,
      category: "Design",
      language: "English",
      level: "Beginner",
      date: "2025-02-18",
      time: "11:00 AM",
      duration: "3 hours",
      price: "899",
      mode: "offline",
      address: "Mumbai Design Studio",
      thumbnailUrl: "https://source.unsplash.com/featured/?ui,ux,design",
      status: "approved",
    },
    {
      slug: "python-data-analysis",
      title: "Python for Data Analysis",
      description: "Analyze data using Pandas, NumPy, and visualization tools.",
      createdBy: ADMIN_USER_ID,
      category: "Data Science",
      language: "English",
      level: "Beginner",
      date: "2025-02-20",
      time: "10:30 AM",
      duration: "3.5 hours",
      price: "1199",
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?python,data",
      status: "approved",
    },
    {
      slug: "machine-learning-foundations",
      title: "Machine Learning Foundations",
      description: "Understand ML algorithms, models, and real use cases.",
      createdBy: ADMIN_USER_ID,
      category: "Machine Learning",
      language: "English",
      level: "Beginner",
      date: "2025-02-22",
      time: "01:00 PM",
      duration: "4 hours",
      price: "1799",
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?machinelearning,ai",
      status: "approved",
    },
    {
      slug: "devops-ci-cd-pipelines",
      title: "DevOps & CI/CD Pipelines",
      description: "Learn Docker, CI/CD pipelines, and cloud deployment.",
      createdBy: ADMIN_USER_ID,
      category: "DevOps",
      language: "English",
      level: "Intermediate",
      date: "2025-02-25",
      time: "03:00 PM",
      duration: "4 hours",
      price: "1999",
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?devops,cloud",
      status: "pending",
    },
    {
      slug: "cyber-security-essentials",
      title: "Cyber Security Essentials",
      description:
        "Basics of ethical hacking, vulnerabilities, and security tools.",
      createdBy: ADMIN_USER_ID,
      category: "Cyber Security",
      language: "English",
      level: "Beginner",
      date: "2025-02-28",
      time: "12:00 PM",
      duration: "3 hours",
      price: "1299",
      mode: "online",
      address: null,
      thumbnailUrl:
        "https://source.unsplash.com/featured/?cybersecurity,hacking",
      status: "approved",
    },
    {
      slug: "nextjs-production-apps",
      title: "Next.js Production Apps",
      description: "Build SEO-friendly, scalable apps using Next.js.",
      createdBy: ADMIN_USER_ID,
      category: "Web Development",
      language: "English",
      level: "Advanced",
      date: "2025-03-02",
      time: "11:00 AM",
      duration: "5 hours",
      price: "2499",
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?nextjs,react",
      status: "approved",
    },
    {
      slug: "database-design-optimization",
      title: "Database Design & Optimization",
      description: "Design efficient databases with indexing and query tuning.",
      createdBy: ADMIN_USER_ID,
      category: "Database",
      language: "English",
      level: "Intermediate",
      date: "2025-03-05",
      time: "02:00 PM",
      duration: "4 hours",
      price: "1899",
      mode: "both",
      address: "Hyderabad IT Park",
      thumbnailUrl: "https://source.unsplash.com/featured/?database,sql",
      status: "approved",
    },

    // ---------- EXTRA 10 ----------
    {
      slug: "aws-cloud-fundamentals",
      title: "AWS Cloud Fundamentals",
      description: "Learn EC2, S3, IAM, and cloud architecture basics.",
      createdBy: ADMIN_USER_ID,
      category: "Cloud",
      language: "English",
      level: "Beginner",
      date: "2025-03-08",
      time: "10:00 AM",
      duration: "3 hours",
      price: "1399",
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?aws,cloud",
      status: "approved",
    },
    {
      slug: "mobile-app-react-native",
      title: "Mobile App Development with React Native",
      description: "Build Android & iOS apps using React Native.",
      createdBy: ADMIN_USER_ID,
      category: "Mobile Development",
      language: "English",
      level: "Intermediate",
      date: "2025-03-10",
      time: "01:00 PM",
      duration: "5 hours",
      price: "2299",
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?mobile,app",
      status: "pending",
    },
    {
      slug: "figma-ui-design-workshop",
      title: "Figma UI Design Workshop",
      description: "Design modern interfaces using Figma.",
      createdBy: ADMIN_USER_ID,
      category: "Design",
      language: "English",
      level: "Beginner",
      date: "2025-03-12",
      time: "11:30 AM",
      duration: "3 hours",
      price: "799",
      mode: "offline",
      address: "Delhi Design Lab",
      thumbnailUrl: "https://source.unsplash.com/featured/?figma,design",
      status: "approved",
    },
    {
      slug: "blockchain-basics",
      title: "Blockchain Basics",
      description: "Understand blockchain, smart contracts, and Web3.",
      createdBy: ADMIN_USER_ID,
      category: "Blockchain",
      language: "English",
      level: "Beginner",
      date: "2025-03-14",
      time: "12:00 PM",
      duration: "3.5 hours",
      price: "1699",
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?blockchain,crypto",
      status: "approved",
    },
    {
      slug: "software-testing-automation",
      title: "Software Testing & Automation",
      description: "Manual + automation testing with Selenium.",
      createdBy: ADMIN_USER_ID,
      category: "Testing",
      language: "English",
      level: "Intermediate",
      date: "2025-03-16",
      time: "02:30 PM",
      duration: "4 hours",
      price: "1599",
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?software,testing",
      status: "approved",
    },
  ]);
  console.log("✅ Workshops seeded successfully");
}
