import { db } from "./drizzle";
import { workshops } from "./schema";

const ADMIN_USER_ID = "L3USi2X66cZpFhIBegzYX3zctsqXJ1cp";

export async function seedWorkshops() {
  await db.insert(workshops).values([
    // ================= Art & Creativity =================
    {
      slug: "watercolor-painting-basics",
      title: "Watercolor Painting Basics",
      description: "Learn fundamental watercolor techniques and color theory.",
      createdBy: ADMIN_USER_ID,
      category: "Art & Creativity",
      language: "English",
      level: "Beginner",
      date: "2025-02-10",
      time: "10:00 AM",
      duration: "3 hours",
      price: 799,
      mode: "offline",
      address: "Mumbai Art Studio",
      thumbnailUrl: "https://source.unsplash.com/featured/?watercolor,art",
      status: "approved",
      rating: 4,
    },
    {
      slug: "digital-art-with-procreate",
      title: "Digital Art with Procreate",
      description: "Create stunning digital illustrations using Procreate.",
      createdBy: ADMIN_USER_ID,
      category: "Art & Creativity",
      language: "English",
      level: "Intermediate",
      date: "2025-02-12",
      time: "02:00 PM",
      duration: "4 hours",
      price: 1199,
      mode: "online",
      address: null,
      thumbnailUrl:
        "https://source.unsplash.com/featured/?digital-art,illustration",
      status: "approved",
      rating: 5,
    },

    // ================= Music & Performance =================
    {
      slug: "guitar-for-beginners",
      title: "Guitar for Beginners",
      description: "Learn chords, strumming patterns, and basic songs.",
      createdBy: ADMIN_USER_ID,
      category: "Music & Performance",
      language: "English",
      level: "Beginner",
      date: "2025-02-15",
      time: "11:00 AM",
      duration: "3 hours",
      price: 999,
      mode: "offline",
      address: "Delhi Music Academy",
      thumbnailUrl: "https://source.unsplash.com/featured/?guitar,music",
      status: "approved",
      rating: 4,
    },
    {
      slug: "vocal-training-masterclass",
      title: "Vocal Training Masterclass",
      description: "Improve pitch, tone, and vocal control.",
      createdBy: ADMIN_USER_ID,
      category: "Music & Performance",
      language: "English",
      level: "Intermediate",
      date: "2025-02-18",
      time: "01:00 PM",
      duration: "4 hours",
      price: 1499,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?singing,vocal",
      status: "approved",
      rating: 5,
    },

    // ================= Technology & Coding =================
    {
      slug: "javascript-from-scratch",
      title: "JavaScript from Scratch",
      description: "Understand JS fundamentals and real-world usage.",
      createdBy: ADMIN_USER_ID,
      category: "Technology & Coding",
      language: "English",
      level: "Beginner",
      date: "2025-02-20",
      time: "10:00 AM",
      duration: "4 hours",
      price: 999,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?javascript,coding",
      status: "approved",
      rating: 4,
    },
    {
      slug: "react-advanced-patterns",
      title: "React Advanced Patterns",
      description: "Learn advanced hooks, patterns, and performance tips.",
      createdBy: ADMIN_USER_ID,
      category: "Technology & Coding",
      language: "English",
      level: "Advanced",
      date: "2025-02-22",
      time: "02:00 PM",
      duration: "5 hours",
      price: 1999,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?react,frontend",
      status: "approved",
      rating: 5,
    },

    // ================= Languages =================
    {
      slug: "spoken-english-confidence",
      title: "Spoken English for Confidence",
      description: "Improve fluency and everyday conversation skills.",
      createdBy: ADMIN_USER_ID,
      category: "Languages",
      language: "English",
      level: "Beginner",
      date: "2025-02-24",
      time: "09:00 AM",
      duration: "3 hours",
      price: 699,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?english,language",
      status: "approved",
      rating: 4,
    },
    {
      slug: "basic-french-speaking",
      title: "Basic French Speaking",
      description: "Learn everyday French phrases and pronunciation.",
      createdBy: ADMIN_USER_ID,
      category: "Languages",
      language: "French",
      level: "Beginner",
      date: "2025-02-26",
      time: "11:00 AM",
      duration: "3 hours",
      price: 899,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?french,language",
      status: "approved",
      rating: 4,
    },

    // ================= Business & Money =================
    {
      slug: "personal-finance-basics",
      title: "Personal Finance Basics",
      description: "Budgeting, saving, and smart investing explained.",
      createdBy: ADMIN_USER_ID,
      category: "Business & Money",
      language: "English",
      level: "Beginner",
      date: "2025-02-28",
      time: "10:30 AM",
      duration: "3 hours",
      price: 799,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?finance,money",
      status: "approved",
      rating: 4,
    },
    {
      slug: "startup-business-models",
      title: "Startup Business Models",
      description: "Learn how successful startups make money.",
      createdBy: ADMIN_USER_ID,
      category: "Business & Money",
      language: "English",
      level: "Intermediate",
      date: "2025-03-02",
      time: "01:00 PM",
      duration: "4 hours",
      price: 1499,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?startup,business",
      status: "approved",
      rating: 5,
    },

    // ================= Health & Fitness =================
    {
      slug: "yoga-for-beginners",
      title: "Yoga for Beginners",
      description: "Improve flexibility, breathing, and posture.",
      createdBy: ADMIN_USER_ID,
      category: "Health & Fitness",
      language: "English",
      level: "Beginner",
      date: "2025-03-04",
      time: "07:00 AM",
      duration: "2 hours",
      price: 599,
      mode: "offline",
      address: "Bangalore Yoga Center",
      thumbnailUrl: "https://source.unsplash.com/featured/?yoga,fitness",
      status: "approved",
      rating: 4,
    },
    {
      slug: "home-workout-training",
      title: "Home Workout Training",
      description: "Full-body workouts without gym equipment.",
      createdBy: ADMIN_USER_ID,
      category: "Health & Fitness",
      language: "English",
      level: "Intermediate",
      date: "2025-03-06",
      time: "06:00 AM",
      duration: "2.5 hours",
      price: 699,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?workout,fitness",
      status: "approved",
      rating: 4,
    },

    // ================= Cooking & Lifestyle =================
    {
      slug: "indian-home-cooking",
      title: "Indian Home Cooking",
      description: "Cook everyday Indian meals with ease.",
      createdBy: ADMIN_USER_ID,
      category: "Cooking & Lifestyle",
      language: "English",
      level: "Beginner",
      date: "2025-03-08",
      time: "11:00 AM",
      duration: "3 hours",
      price: 899,
      mode: "offline",
      address: "Pune Cooking Studio",
      thumbnailUrl: "https://source.unsplash.com/featured/?indian-food,cooking",
      status: "approved",
      rating: 5,
    },
    {
      slug: "healthy-meal-prep",
      title: "Healthy Meal Prep",
      description: "Plan and cook healthy meals for the week.",
      createdBy: ADMIN_USER_ID,
      category: "Cooking & Lifestyle",
      language: "English",
      level: "Intermediate",
      date: "2025-03-10",
      time: "12:00 PM",
      duration: "3 hours",
      price: 999,
      mode: "online",
      address: null,
      thumbnailUrl:
        "https://source.unsplash.com/featured/?healthy-food,meal-prep",
      status: "approved",
      rating: 4,
    },

    // ================= Professional Skills =================
    {
      slug: "resume-building-workshop",
      title: "Resume Building Workshop",
      description: "Create a strong resume that gets interviews.",
      createdBy: ADMIN_USER_ID,
      category: "Professional Skills",
      language: "English",
      level: "Beginner",
      date: "2025-03-12",
      time: "02:00 PM",
      duration: "2 hours",
      price: 499,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?resume,career",
      status: "approved",
      rating: 4,
    },
    {
      slug: "interview-preparation-masterclass",
      title: "Interview Preparation Masterclass",
      description: "Ace HR and technical interviews with confidence.",
      createdBy: ADMIN_USER_ID,
      category: "Professional Skills",
      language: "English",
      level: "Intermediate",
      date: "2025-03-14",
      time: "03:00 PM",
      duration: "3 hours",
      price: 999,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?interview,job",
      status: "approved",
      rating: 5,
    },

    // ================= Personal Development =================
    {
      slug: "time-management-skills",
      title: "Time Management Skills",
      description: "Learn productivity and goal-setting techniques.",
      createdBy: ADMIN_USER_ID,
      category: "Personal Development",
      language: "English",
      level: "Beginner",
      date: "2025-03-16",
      time: "10:00 AM",
      duration: "2.5 hours",
      price: 599,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?productivity,time",
      status: "approved",
      rating: 4,
    },
    {
      slug: "confidence-building-workshop",
      title: "Confidence Building Workshop",
      description: "Develop self-confidence and communication skills.",
      createdBy: ADMIN_USER_ID,
      category: "Personal Development",
      language: "English",
      level: "Intermediate",
      date: "2025-03-18",
      time: "01:00 PM",
      duration: "3 hours",
      price: 899,
      mode: "offline",
      address: "Chennai Training Center",
      thumbnailUrl: "https://source.unsplash.com/featured/?confidence,mindset",
      status: "approved",
      rating: 5,
    },

    // ================= Writing & Communication =================
    {
      slug: "creative-writing-basics",
      title: "Creative Writing Basics",
      description: "Learn storytelling, structure, and creativity.",
      createdBy: ADMIN_USER_ID,
      category: "Writing & Communication",
      language: "English",
      level: "Beginner",
      date: "2025-03-20",
      time: "11:00 AM",
      duration: "3 hours",
      price: 699,
      mode: "online",
      address: null,
      thumbnailUrl: "https://source.unsplash.com/featured/?writing,creative",
      status: "approved",
      rating: 4,
    },
    {
      slug: "public-speaking-skills",
      title: "Public Speaking Skills",
      description: "Speak confidently in meetings and presentations.",
      createdBy: ADMIN_USER_ID,
      category: "Writing & Communication",
      language: "English",
      level: "Intermediate",
      date: "2025-03-22",
      time: "02:00 PM",
      duration: "3 hours",
      price: 999,
      mode: "offline",
      address: "Hyderabad Communication Lab",
      thumbnailUrl:
        "https://source.unsplash.com/featured/?public-speaking,speech",
      status: "approved",
      rating: 5,
    },
  ]);

  console.log("✅ 20 category-based workshops seeded successfully");
}
